export const IncidentType = {
  ACCIDENT: "ACCIDENT",
  CONSTRUCTION: "CONSTRUCTION",
  CLOSURE: "CLOSURE",
  HAZARD: "HAZARD",
  TRAFFIC_JAM: "TRAFFIC_JAM",
};

export const SeverityLevel = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
};

export const ReportStatus = {
  ACTIVE: "ACTIVE",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  NEEDS_CHANGES: "NEEDS_CHANGES",
  RESOLVED: "RESOLVED",
  EXPIRED: "EXPIRED",
};
